# -*- coding: utf-8 -*-
"""Credit_Card_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFw9qTlmK5Xj-t8O4xUCaDjW_Al2k96e
"""

# CODSOFT : DATA SCIENCE
# TASK 5 : CREDIT CARD FRAUD DETECTION USING MACHINE LEARNING
# AUTHOR : SALIK KHAN



import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

print("Libraries Imported Successfully")

# INSTALL & LOAD KAGGLE DATASET



!pip install kagglehub -q

import kagglehub
import os

print("\nDownloading Dataset From Kaggle...")

dataset_path = kagglehub.dataset_download(
    "mlg-ulb/creditcardfraud"
)

print("Dataset Path:")
print(dataset_path)

# Load Dataset

df = pd.read_csv(
    os.path.join(
        dataset_path,
        "creditcard.csv"
    )
)

print("\nDataset Loaded Successfully!")


# BASIC INFORMATION


print("\n" + "="*60)
print("DATASET OVERVIEW")
print("="*60)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

print("\nFirst 5 Records")
print(df.head())

# DATA QUALITY REPORT

print("\n" + "="*60)
print("DATA QUALITY REPORT")
print("="*60)

duplicates = df.duplicated().sum()

missing_values = df.isnull().sum().sum()

print(f"Duplicate Records : {duplicates}")
print(f"Missing Values    : {missing_values}")

if duplicates > 0:

    df.drop_duplicates(
        inplace=True
    )

    print(
        f"{duplicates} duplicate rows removed."
    )

else:

    print(
        "No duplicate records found."
    )

quality_report = pd.DataFrame({

    "Data Type":
        df.dtypes,

    "Missing Values":
        df.isnull().sum(),

    "Unique Values":
        df.nunique()
})

print("\nQuality Report")
print(quality_report.head(10))

# DATASET INFORMATION

print("\nDataset Information")
print(df.info())

print("\nStatistical Summary")
print(df.describe())

# FRAUD ANALYSIS

print("\n" + "="*60)
print("FRAUD ANALYSIS")
print("="*60)

fraud_count = df["Class"].value_counts()

print(fraud_count)

fraud_percentage = (

    df["Class"]
    .value_counts(
        normalize=True
    ) * 100
)

print("\nPercentage Distribution")

print(fraud_percentage)

# CLASS DISTRIBUTION

plt.figure(figsize=(7,5))

sns.countplot(
    x="Class",
    data=df
)

plt.title(
    "Fraud vs Genuine Transactions"
)

plt.xlabel("Class")

plt.ylabel("Count")

plt.show()

# PIE CHART

plt.figure(figsize=(6,6))

plt.pie(
    fraud_count,
    labels=[
        "Genuine",
        "Fraud"
    ],
    autopct="%1.2f%%"
)

plt.title(
    "Transaction Distribution"
)

plt.show()

# TRANSACTION AMOUNT DISTRIBUTION

plt.figure(figsize=(8,5))

sns.histplot(
    df["Amount"],
    bins=50,
    kde=True
)

plt.title(
    "Transaction Amount Distribution"
)

plt.show()

# TRANSACTION AMOUNT BY CLASS

plt.figure(figsize=(8,5))

sns.boxplot(
    x="Class",
    y="Amount",
    data=df
)

plt.title(
    "Transaction Amount By Class"
)

plt.show()

# CORRELATION ANALYSIS

corr_with_target = (

    df.corr()["Class"]
    .sort_values(
        ascending=False
    )
)

print("\nTop Correlated Features")

print(
    corr_with_target.head(10)
)

print("\nMost Negative Features")

print(
    corr_with_target.tail(10)
)

# HEATMAP

plt.figure(
    figsize=(12,8)
)

sns.heatmap(
    df.corr(),
    cmap="coolwarm"
)

plt.title(
    "Correlation Heatmap"
)

plt.show()


# PREPROCESSING & CLASS IMBALANCE HANDLING

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTETomek

print("\n" + "="*60)
print("PREPROCESSING PIPELINE")
print("="*60)

# SCALE AMOUNT & TIME

scaler = StandardScaler()

df["Amount_Scaled"] = scaler.fit_transform(
    df[["Amount"]]
)

df["Time_Scaled"] = scaler.fit_transform(
    df[["Time"]]
)

print("Amount and Time Scaling Completed")

# REMOVE ORIGINAL COLUMNS

df_processed = df.drop(
    columns=[
        "Amount",
        "Time"
    ]
)

print("Original Amount and Time Columns Removed")

# FEATURES & TARGET

X = df_processed.drop(
    "Class",
    axis=1
)

y = df_processed["Class"]

print("\nFeature Matrix Shape :", X.shape)
print("Target Vector Shape  :", y.shape)

# CLASS DISTRIBUTION

print("\nOriginal Class Distribution")

print(
    y.value_counts()
)

print(
    "\nFraud Percentage : "
    f"{round(y.mean()*100,4)}%"
)

# TRAIN TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y
)

print("\nTrain Test Split Completed")

print(f"X_train : {X_train.shape}")
print(f"X_test  : {X_test.shape}")

print(f"y_train : {y_train.shape}")
print(f"y_test  : {y_test.shape}")

# SMOTE OVERSAMPLING

print("\nApplying SMOTE...")

smote = SMOTE(
    random_state=42,
    k_neighbors=5
)

X_smote, y_smote = smote.fit_resample(
    X_train,
    y_train
)

print("SMOTE Completed")

print(
    pd.Series(y_smote)
    .value_counts()
)

# RANDOM UNDERSAMPLING

print("\nApplying Random Under Sampling...")

rus = RandomUnderSampler(
    random_state=42
)

X_under, y_under = rus.fit_resample(
    X_train,
    y_train
)

print("Under Sampling Completed")

print(
    pd.Series(y_under)
    .value_counts()
)

# SMOTETOMEK (HYBRID)

print("\nApplying SMOTETomek...")

smt = SMOTETomek(
    random_state=42
)

X_hybrid, y_hybrid = smt.fit_resample(
    X_train,
    y_train
)

print("SMOTETomek Completed")

print(
    pd.Series(y_hybrid)
    .value_counts()
)

# VISUALIZE RESAMPLING RESULTS

fig, axes = plt.subplots(
    1,
    4,
    figsize=(18,5)
)

datasets = [

    ("Original", y_train),

    ("SMOTE", y_smote),

    ("Under Sample", y_under),

    ("SMOTETomek", y_hybrid)
]

for ax, (title, labels) in zip(
    axes,
    datasets
):

    counts = pd.Series(
        labels
    ).value_counts()

    ax.bar(
        ["Genuine","Fraud"],
        counts.values
    )

    ax.set_title(title)

    ax.set_ylabel(
        "Count"
    )

plt.tight_layout()

plt.show()

# DATA READY FOR MODEL TRAINING

print("\nData Preparation Completed Successfully")

print("\nTraining Data To Be Used:")

print(f"X_smote : {X_smote.shape}")
print(f"y_smote : {y_smote.shape}")

# MODEL TRAINING & COMPARISON

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)

from sklearn.metrics import (

    precision_score,

    recall_score,

    f1_score,

    roc_auc_score
)

print("\n" + "="*60)
print("MODEL TRAINING")
print("="*60)

# MODEL DEFINITIONS

models = {

    "Logistic Regression":

        LogisticRegression(

            max_iter=1000,

            random_state=42,

            class_weight="balanced",

            C=0.1
        ),

    "Random Forest":

        RandomForestClassifier(

            n_estimators=100,

            random_state=42,

            class_weight="balanced",

            n_jobs=-1,

            max_depth=10,

            min_samples_leaf=5
        ),

    "Gradient Boosting":

        GradientBoostingClassifier(

            n_estimators=100,

            random_state=42,

            learning_rate=0.1,

            max_depth=5,

            subsample=0.8
        )
}

# TRAIN MODELS USING SMOTE DATA

results = {}

for name, model in models.items():

    print(f"\nTraining {name}...")

    model.fit(
        X_smote,
        y_smote
    )

    y_pred = model.predict(
        X_test
    )

    y_prob = model.predict_proba(
        X_test
    )[:,1]

    precision = precision_score(
        y_test,
        y_pred
    )

    recall = recall_score(
        y_test,
        y_pred
    )

    f1 = f1_score(
        y_test,
        y_pred
    )

    roc_auc = roc_auc_score(
        y_test,
        y_prob
    )

    results[name] = {

        "model":
            model,

        "y_pred":
            y_pred,

        "y_prob":
            y_prob,

        "Precision":
            precision,

        "Recall":
            recall,

        "F1 Score":
            f1,

        "ROC-AUC":
            roc_auc
    }

    print(
        f"Precision : {precision:.4f}"
    )

    print(
        f"Recall    : {recall:.4f}"
    )

    print(
        f"F1 Score  : {f1:.4f}"
    )

    print(
        f"ROC-AUC   : {roc_auc:.4f}"
    )

# MODEL COMPARISON TABLE

metrics_df = pd.DataFrame({

    name: {

        "Precision":
            values["Precision"],

        "Recall":
            values["Recall"],

        "F1 Score":
            values["F1 Score"],

        "ROC-AUC":
            values["ROC-AUC"]

    }

    for name, values
    in results.items()

}).T

metrics_df = metrics_df.round(4)

print("\n" + "="*60)
print("MODEL COMPARISON")
print("="*60)

print(metrics_df)

# MODEL COMPARISON VISUALIZATION

fig, axes = plt.subplots(

    1,

    4,

    figsize=(18,5)
)

metric_names = [

    "Precision",

    "Recall",

    "F1 Score",

    "ROC-AUC"
]

for ax, metric in zip(

    axes,

    metric_names
):

    sns.barplot(

        x=metrics_df.index,

        y=metrics_df[metric],

        ax=ax
    )

    ax.set_title(metric)

    ax.set_ylabel("Score")

    ax.tick_params(

        axis="x",

        rotation=15
    )

plt.tight_layout()

plt.show()

# BEST MODEL SELECTION

best_model_name = (

    metrics_df["F1 Score"]

    .idxmax()
)

best_model = (

    results[best_model_name]

    ["model"]
)

print("\n" + "="*60)
print("BEST MODEL SELECTED")
print("="*60)

print(

    f"Best Model : "
    f"{best_model_name}"
)

print(

    f"F1 Score   : "
    f"{metrics_df.loc[best_model_name,'F1 Score']:.4f}"
)

print(

    f"ROC-AUC    : "
    f"{metrics_df.loc[best_model_name,'ROC-AUC']:.4f}"
)



# MODEL EVALUATION DASHBOARD

from sklearn.metrics import (

    classification_report,

    confusion_matrix,

    roc_curve,

    precision_recall_curve,

    average_precision_score
)

print("\n" + "="*60)
print("MODEL EVALUATION")
print("="*60)

# CLASSIFICATION REPORTS

for name, values in results.items():

    print("\n" + "="*60)

    print(f"{name}")

    print("="*60)

    print(

        classification_report(

            y_test,

            values["y_pred"],

            target_names=[

                "Genuine",

                "Fraud"
            ]
        )
    )

# CONFUSION MATRICES

fig, axes = plt.subplots(

    1,

    3,

    figsize=(18,5)
)

for ax, (name, values) in zip(

    axes,

    results.items()
):

    cm = confusion_matrix(

        y_test,

        values["y_pred"]
    )

    sns.heatmap(

        cm,

        annot=True,

        fmt="d",

        cmap="Blues",

        ax=ax
    )

    ax.set_title(

        f"{name}\nConfusion Matrix"
    )

    ax.set_xlabel(
        "Predicted"
    )

    ax.set_ylabel(
        "Actual"
    )

plt.tight_layout()

plt.show()

# ROC CURVES

plt.figure(figsize=(8,6))

for name, values in results.items():

    fpr, tpr, _ = roc_curve(

        y_test,

        values["y_prob"]
    )

    plt.plot(

        fpr,

        tpr,

        label=f"{name} (AUC = {values['ROC-AUC']:.4f})"
    )

plt.plot(

    [0,1],

    [0,1],

    linestyle="--"
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ROC Curve Comparison"
)

plt.legend()

plt.grid(True)

plt.show()

# PRECISION RECALL CURVES



plt.figure(figsize=(8,6))

for name, values in results.items():

    precision, recall, _ = precision_recall_curve(

        y_test,

        values["y_prob"]
    )

    avg_precision = average_precision_score(

        y_test,

        values["y_prob"]
    )

    plt.plot(

        recall,

        precision,

        label=f"{name} (AP = {avg_precision:.4f})"
    )

plt.xlabel(
    "Recall"
)

plt.ylabel(
    "Precision"
)

plt.title(
    "Precision Recall Curve"
)

plt.legend()

plt.grid(True)

plt.show()



# EVALUATION SUMMARY

print("\n" + "="*60)
print("EVALUATION SUMMARY")
print("="*60)

print(metrics_df)

print("\nBest Performing Model:")
print(best_model_name)

# FINAL DEPLOYMENT & BUSINESS INSIGHTS

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score
)

import joblib

print("\n" + "="*60)
print("FEATURE IMPORTANCE ANALYSIS")
print("="*60)

# FEATURE IMPORTANCE

if best_model_name == "Random Forest":

    feature_importance = pd.DataFrame({

        "Feature":
            X.columns,

        "Importance":
            best_model.feature_importances_

    })

    feature_importance = (

        feature_importance

        .sort_values(

            by="Importance",

            ascending=False
        )
    )

    print("\nTop 20 Important Features")

    print(
        feature_importance.head(20)
    )

    plt.figure(
        figsize=(10,6)
    )

    sns.barplot(

        data=feature_importance.head(20),

        x="Importance",

        y="Feature"
    )

    plt.title(
        "Top 20 Feature Importance"
    )

    plt.show()

# THRESHOLD TUNING

print("\n" + "="*60)
print("THRESHOLD OPTIMIZATION")
print("="*60)

best_probabilities = results[
    best_model_name
]["y_prob"]

thresholds = np.arange(
    0.05,
    0.95,
    0.01
)

f1_scores = []

for threshold in thresholds:

    predictions = (

        best_probabilities >= threshold

    ).astype(int)

    score = f1_score(
        y_test,
        predictions
    )

    f1_scores.append(score)

best_threshold = thresholds[
    np.argmax(f1_scores)
]

best_f1 = max(
    f1_scores
)

print(
    f"Best Threshold : {best_threshold:.2f}"
)

print(
    f"Best F1 Score  : {best_f1:.4f}"
)

plt.figure(
    figsize=(10,5)
)

plt.plot(
    thresholds,
    f1_scores
)

plt.axvline(
    best_threshold,
    color="red",
    linestyle="--"
)

plt.title(
    "Threshold Optimization"
)

plt.xlabel(
    "Threshold"
)

plt.ylabel(
    "F1 Score"
)

plt.grid(True)

plt.show()

# FRAUD DETECTION EXAMPLE

print("\n" + "="*60)
print("FRAUD DETECTION EXAMPLE")
print("="*60)

sample_transaction = X_test.iloc[[0]]

prediction = best_model.predict(
    sample_transaction
)

probability = best_model.predict_proba(
    sample_transaction
)[0][1]

print(
    f"Prediction : "
    f"{'Fraud' if prediction[0] == 1 else 'Genuine'}"
)

print(
    f"Fraud Probability : "
    f"{probability:.4f}"
)

# SAVE MODEL

joblib.dump(

    best_model,

    "credit_card_fraud_detector.pkl"
)

print(
    "\nModel Saved Successfully!"
)

print(
    "File Name : credit_card_fraud_detector.pkl"
)

# FINAL PROJECT SUMMARY

summary = pd.DataFrame({

    "Metric": [

        "Best Model",

        "Precision",

        "Recall",

        "F1 Score",

        "ROC-AUC",

        "Optimal Threshold",

        "Fraud Transactions",

        "Total Transactions"

    ],

    "Value": [

        best_model_name,

        round(
            metrics_df.loc[
                best_model_name,
                "Precision"
            ],
            4
        ),

        round(
            metrics_df.loc[
                best_model_name,
                "Recall"
            ],
            4
        ),

        round(
            metrics_df.loc[
                best_model_name,
                "F1 Score"
            ],
            4
        ),

        round(
            metrics_df.loc[
                best_model_name,
                "ROC-AUC"
            ],
            4
        ),

        round(
            best_threshold,
            2
        ),

        int(
            y.sum()
        ),

        int(
            len(y)
        )
    ]
})

print("\n" + "="*60)
print("PROJECT SUMMARY")
print("="*60)

print(summary)

# BUSINESS INSIGHTS

print("\n" + "="*60)
print("BUSINESS INSIGHTS")
print("="*60)

print(
    "• Fraud transactions represent a very small percentage of all transactions."
)

print(
    "• Class imbalance handling significantly improves fraud detection."
)

print(
    "• SMOTE helps the model learn fraud patterns more effectively."
)

print(
    "• High Recall is critical because missing a fraud transaction can lead to financial loss."
)

print(
    "• High Precision reduces unnecessary fraud alerts."
)

print(
    "• The model can assist banks and financial institutions in fraud prevention."
)

print(
    "• Threshold optimization improves overall detection performance."
)

# FINAL MESSAGE

print("\n" + "="*60)

print("="*60)

print(
    "\nCredit Card Fraud Detection Project Finished."
)

print(
    "Model Ready For Deployment & Business Analysis."
)